name: Push - Build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Node Packages
        run: npm ci --no-fund
      - name: Build React App
        run: npm run build
      - name: Test React App
        run: npm run test
